### ISSUE TITLE
--bin in source is shown as -bin on the site

### ISSUE THREAD

**Issue by avrong** [notryanb/notryanb.github.io#16]
Source:
![image](https://user-images.githubusercontent.com/6342851/32697011-3dea2376-c797-11e7-85cb-19fec34ede57.png)

Website:
![image](https://user-images.githubusercontent.com/6342851/32697008-1e856694-c797-11e7-8602-375411e91118.png)

**Comment by notryanb** [comment]
I'll look into why markdown isn't converting this correctly. Thanks!
